# - name: Install lxml
#   become: true
#   ansible.builtin.package:
#     name: "python3-lxml"
#     state: present
#   when: ansible_os_family == "RedHat"
# - name: Download logscale
#   community.general.maven_artifact:
#     group_id: com.humio
#     artifact_id: server-linux_x64
#     extension: tar.gz
#     repository_url: 'https://repo.humio.com/repository/maven-releases/'
#     version: 1.159.1

- name: Download logscale
  become: true
  ansible.builtin.get_url:
    url: "{{ logscale__download_url }}"
    dest: "{{ logscale__download_destination }}"
    mode: "0644"
    timeout: 90
    checksum: "sha256:{{ logscale_checksum }}"
  retries: 3
  delay: 3
  register: download_logscale
  notify: Restart logscale

- name: Unpack logscale
  become: true
  ansible.builtin.unarchive:
    src: "{{ logscale__download_destination }}"
    # creates: true
    copy: false
    dest: "{{ logscale_download_directory }}"
    owner: "root"
    group: "root"
    extra_opts:
    - --transform
    - s/^humio/logscale-{{ logscale_version}}/
  when: download_logscale.changed

- name: Configure logscale symlink
  become: true
  ansible.builtin.file:
    path: "{{ logscale_home }}"
    src: "{{ logscale_download_directory }}/logscale-{{ logscale_version }}"
    state: link
    force: true
    follow: false
  when: download_logscale.changed

- name: Create logscale data and log directories
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ logscale_user }}"
    group: "{{ logscale_user_group }}"
    mode: "0750"
  loop: 
    - "{{ logscale_log_directory }}/audit"
    - "{{ logscale_log_directory }}/debug"
    - "{{ logscale_log_directory }}/jvm"
    - "{{ logscale_directory }}"
    - "{{ logscale_directory }}/data"

- name: Ensure sysconfig directory exists
  become: true
  ansible.builtin.file:
    path: /etc/sysconfig
    state: directory
    mode: "0755"

- name: Install logscale server configuration
  become: true
  ansible.builtin.template:
    src: logscale.j2
    dest: /etc/sysconfig/logscale
    mode: "0644"
  notify: Restart logscale

- name: Install logscale service definition
  become: true
  ansible.builtin.template:
    src: logscale.service.j2
    dest: /usr/lib/systemd/system/logscale.service
    mode: "0644"
  notify: Restart logscale

# - name: Flush handlers
#   ansible.builtin.meta: flush_handlers

# - name: Ensure logscale service is enabled and started
#   become: true
#   ansible.builtin.systemd:
#     name: logscale
#     enabled: true
#     state: started
#     daemon_reload: true
#   retries: 3
#   delay: 2

# - name: Wait for logscale to start
#   ansible.builtin.wait_for:
#     port: 8080
#     timeout: 30
